In [418]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score,r2_score
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

In [420]:
df = pd.read_csv('Fertilizer Prediction.csv')

In [620]:
data = pd.read_csv('Fertilizer Prediction.csv')

In [422]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [596]:
df['Fertilizer Name'].unique()

array([6, 5, 1, 4, 2, 3, 0])

In [600]:
data['Fertilizer Name'].unique()

array(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20',
       '10-26-26'], dtype=object)

In [630]:
import pandas as pd

# Assuming 'df' is your DataFrame
encoded_labels, unique_categories = pd.factorize(data['Fertilizer Name'])

In [634]:
unique_categories

Index(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20', '10-26-26'], dtype='object')

In [424]:
le = LabelEncoder()
df['Soil Type'] = le.fit_transform(df['Soil Type'])
df['Crop Type'] = le.fit_transform(df['Crop Type'])
df['Fertilizer Name'] = le.fit_transform(df['Fertilizer Name'])

In [448]:
df

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0            26         52        38          4          3        37   
1            29         52        45          2          8        12   
2            34         65        62          0          1         7   
3            32         62        34          3          9        22   
4            28         54        46          1          6        35   
..          ...        ...       ...        ...        ...       ...   
94           25         50        32          1          7        24   
95           30         60        27          3          9         4   
96           38         72        51          2         10        39   
97           36         60        43          4          4        15   
98           29         58        57          0          8        12   

    Potassium  Phosphorous  Fertilizer Name  
0           0            0                6  
1           0           36                5  
2           9           30                1  
3           0           20                4  
4           0            0                6  
..        ...          ...              ...  
94          0           19                4  
95         17           17                0  
96          0            0                6  
97          0           41                5  
98          0           10                3  

[99 rows x 9 columns]

In [652]:
df['Fertilizer Name'].unique()

array([6, 5, 1, 4, 2, 3, 0])

In [654]:
data['Fertilizer Name'].unique()

array(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20',
       '10-26-26'], dtype=object)

In [428]:
x = df.drop('Fertilizer Name' , axis =1)
y = df['Fertilizer Name']

In [430]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [575]:
model = LogisticRegression()
model.fit(X_train, y_train)

C:\Users\khans\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [590]:
y_pred = model.predict([[0,52,38,4,3,7,0,0]])
y_pred

C:\Users\khans\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([3])

In [584]:
x

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0            26         52        38          4          3        37   
1            29         52        45          2          8        12   
2            34         65        62          0          1         7   
3            32         62        34          3          9        22   
4            28         54        46          1          6        35   
..          ...        ...       ...        ...        ...       ...   
94           25         50        32          1          7        24   
95           30         60        27          3          9         4   
96           38         72        51          2         10        39   
97           36         60        43          4          4        15   
98           29         58        57          0          8        12   

    Potassium  Phosphorous  
0           0            0  
1           0           36  
2           9           30  
3           0           20  
4           0            0  
..        ...          ...  
94          0           19  
95         17           17  
96          0            0  
97          0           41  
98          0           10  

[99 rows x 8 columns]

In [581]:
accuracy = accuracy_score(y_test, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [20, 1]

In [490]:
accuracy*100

100.0

In [444]:
import pickle

In [549]:
with open('fertilizer_classifier.pkl', 'wb') as file:
    pickle.dump(model, file)

In [551]:
with open('fertilizer_classifier.pkl' , 'rb' ) as file:
    clf = pickle.load(file)
    

In [594]:
prediction = clf.predict([[28,10,40,5,6,79,0,9]])

C:\Users\khans\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [561]:
prediction

array([0])